apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jbosswebservers.web.servers.org
spec:
  group: web.servers.org
  names:
    kind: JbossWebServer
    listKind: JbossWebServerList
    plural: jbosswebservers
    singular: jbosswebserver
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: JbossWebServer is the Schema for the jbosswebservers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: JbossWebServerSpec defines the desired state of JbossWebServer
          properties:
            JbossWebImage:
              description: Image information
              properties:
                applicationImage:
                  description: ApplicationImage is the name of the application image
                    to be deployed
                  type: string
              required:
              - applicationImage
              type: object
            JbossWebImageStream:
              description: ImageStream information
              properties:
                imageStreamName:
                  description: ImageStream containing our images
                  type: string
                imageStreamNamespace:
                  description: Space where the ImageStream is located
                  type: string
              required:
              - imageStreamName
              - imageStreamNamespace
              type: object
            JbossWebServerHealthCheck:
              description: Health checks information
              properties:
                JbossWebServer53HealthCheck:
                  description: Username and Password are for pre 5.4 images
                  properties:
                    jwsAdminPassword:
                      description: Password for the Admin User in the tomcat-users.xml
                      type: string
                    jwsAdminUsername:
                      description: Admin User Name for the tomcat-users.xml
                      type: string
                  required:
                  - jwsAdminPassword
                  - jwsAdminUsername
                  type: object
                serverLivenessScript:
                  description: String for the alive health check logic
                  type: string
                serverReadinessScript:
                  description: String for the readyness health check logic
                  type: string
              required:
              - serverReadinessScript
              type: object
            JbossWebSources:
              description: Sources information
              properties:
                JbossWebSourcesParams:
                  description: Sub not mandatory sources related parameters
                  properties:
                    artifactDir:
                      description: Directory where the jar/war are created.
                      type: string
                    genericWebhookSecret:
                      description: Secret for generic web hook
                      type: string
                    githubWebhookSecret:
                      description: Secret for Github web hook
                      type: string
                    mavenMirrorUrl:
                      description: URL to a maven repository
                      type: string
                  type: object
                contextDir:
                  description: sub directory in the source repository
                  type: string
                sourceRepositoryRef:
                  description: Branch in the source repository
                  type: string
                sourceRepositoryUrl:
                  description: URL for the repository of the application sources
                  type: string
              required:
              - contextDir
              - sourceRepositoryRef
              - sourceRepositoryUrl
              type: object
            applicationName:
              description: ApplicationImage is the name of the application image to
                be deployed
              type: string
            replicas:
              description: Replicas is the desired number of replicas for the application
              format: int32
              minimum: 0
              type: integer
          required:
          - applicationName
          - replicas
          type: object
        status:
          description: JbossWebServerStatus defines the observed state of JbossWebServer
          properties:
            hosts:
              items:
                type: string
              type: array
              x-kubernetes-list-type: set
            pods:
              items:
                description: PodStatus defines the observed state of pods running
                  the JbossWebServer application
                properties:
                  name:
                    type: string
                  podIP:
                    type: string
                  state:
                    description: Represent the state of the Pod, it is used especially
                      during scale down.
                    enum:
                    - ACTIVE
                    - PENDING
                    - FAILED
                    type: string
                required:
                - name
                - podIP
                - state
                type: object
              type: array
              x-kubernetes-list-type: atomic
            replicas:
              description: Replicas is the actual number of replicas for the application
              format: int32
              type: integer
            scalingdownPods:
              description: "Represents the number of pods which are in scaledown process
                what particular pod is scaling down can be verified by PodStatus \n
                Read-only."
              format: int32
              type: integer
          required:
          - replicas
          - scalingdownPods
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
