apiVersion: web.servers.org/v1alpha1
kind: JbossWebServer
metadata:
  name: example-imagestream-jbosswebserver
spec:
  # Add fields here
  applicationName: jws-app
  replicas: 2
  # To use imagestreams, the following fields are required
  JbossWebSources:
    sourceRepositoryUrl: https://github.com/jboss-openshift/openshift-quickstarts.git
    sourceRepositoryRef: "1.2"
    contextDir: tomcat-websocket-chat
    JbossWebSourcesParams:
      #githubWebhookSecret: tomcat
      #genericWebhookSecret: tomcat
      mavenMirrorUrl: ""
      artifactDir: ""
  JbossWebImageStream:
    imageStreamNamespace: openshift
    imageStreamName: jboss-webserver53-tomcat9-openshift
  # For pre JWS-5.4 image you need to set username/password and use the following health check.
  JbossWebServerHealthCheck:
    serverReadinessScript: /bin/bash -c "/usr/bin/curl --noproxy '*' -s -u ${JWS_ADMIN_USERNAME}:${JWS_ADMIN_PASSWORD} 'http://localhost:8080/manager/jmxproxy/?get=Catalina%3Atype%3DServer&att=stateName' | /usr/bin/grep -iq 'stateName *= *STARTED'"
    JbossWebServer53HealthCheck:
      jwsAdminUsername: tomcat
      jwsAdminPassword: tomcat
