apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nfs
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: quay.io/jfclere/nfs
        securityContext:
          privileged: true
        ports:
        - name: nfs
          containerPort: 2049
        volumeMounts:
        - mountPath: /myhome
          name: nfs-for-tomcat
      serviceAccount: nfs-storage-sa
      volumes:
        - name: nfs-for-tomcat
          emptyDir: {}

---

kind: Service
apiVersion: v1
metadata:
  name: nfs-service0
spec:
  ClusterIP: "None"
  ports:
    - name: nfs
      protocol: TCP
      port: 2049
      targetport: "2049"
  selector:
   app: tomcat
